name: citra-transifex

on:
  push:
    branches: [ master ]

jobs:
  transifex:
    runs-on: ubuntu-latest
    container: opensauce04/azahar-build-environment:transifex
    if: ${{ github.repository == 'azahar-emu/azahar' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Update Translation
        run: ./.ci/transifex.sh
        env:
          TX_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
